version: "3"

volumes: 
  db-volume:

services: 
  db:
    image: mysql
    restart: always
    environment: 
      - MYSQL_DATABASE=debt
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - db-volume:/var/lib/mysql
    ports: 
      - 3307:3306

  api:
    build: .
    restart: always
    environment: 
      - DB_URL=jdbc:mysql://db/debt
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on: 
      - db
    ports:
      - 8080:8080
